import { Open_Sans, Oswald } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";

const openSans = Open_Sans({
  subsets: ["latin"],
  weights: [300, 400, 500, 600, 700, 800],
  styles: ["regular", "italic"],
  variable: "--font-openSans",
});

const oswald = Oswald({
  subsets: ["latin"],
  weights: [200, 300, 400, 500, 600, 700, 800],
  styles: ["regular", "italic"],
  variable: "--font-oswald",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${oswald.variable}`}>
        <GoogleOAuthProvider clientId="249472884306-f7svq4q2qgeks5qfnp3vsi22gkr8720a.apps.googleusercontent.com">
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
